### ISSUE TITLE
Conditions, like { name: null } , to query resources can't be used.

### ISSUE THREAD

**Issue by zxh19890103** [feathersjs/rest-client#18]
### Steps to reproduce

To fetch the data on server, I use the FIND method of service.
For example: 
...service('dogs').find({ query: { name: null } }),
where I want to find all the dogs without name (the value of NAME field is NULL)

### Expected behavior
Return all the dogs without name (NULL).

### Actual behavior
ERROR !

**Comment by daffl** [comment]
URL query parameter values will always be strings. Conversion (e.g. the string `'true'` to boolean `true` of `null` values) should be done in a before [hook](https://docs.feathersjs.com/api/hooks.html):

```js
app.service('myservice').hooks({
  before: {
    async find(context) {
      const { query = {} } = context.params;

      if(query.myparam === 'null') {
        query.myparam = null;
      }
    }
  }
});
```

**Comment by zxh19890103** [comment]
Thank @daffl.
I wonder why feathers does not process it for this kind of query is so often.

**Comment by daffl** [comment]
Because Feathers does not know about how your data looks like and what it should convert it to. As you've seen in the example it is fairly easy adjusting everything to your needs. This is also only a limitation when using REST. If you use Socket.io data will arrive in the same format you sent.
