### ISSUE TITLE
Pass request options to transport (request)

### ISSUE THREAD

**Issue by sdbondi** [feathersjs/rest-client#26]
Hi there

Currently, there is no way to pass options to the underlying client library.

For example:

`    .configure(rest(config.url).request(request, {agentOptions: { rejectUnauthorized: false }}))`

In the code it seems like `this.options` in `Base` is not used.

Perhaps doing the following would help: https://github.com/fixate/rest-client/blob/pr/allow-options/lib/request.js#L8

**Comment by daffl** [comment]
This is a good suggestions, specifically for Request though, you can already do this using `request.defaults` as [shown in the documentation](https://docs.feathersjs.com/api/client/rest.html#request):

```js
const request = require('request');
const requestClient = request.defaults({
  rejectUnauthorized: false 
});

app.configure(restClient.request(requestClient));
```
