### ISSUE TITLE
Need a way to abort requests

### ISSUE THREAD

**Issue by anilanar** [feathersjs/rest-client#29]
For `XMLHttpRequest`: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort
For `fetch`: https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal

Sadly, `rest-client` relies on `fetch` API which has abort signals in the spec but not yet implemented by most browser vendors. 

However there's one fetch polyfill that supports it: https://github.com/Netflix/yetch.

The spec is finalized so this can be implemented here.

**Comment by daffl** [comment]
Probably related to #26 - if we're able to pass options to the connection it would "Just work" ™️
