### ISSUE TITLE
Interpolated strings are causing issues with IE 11

### ISSUE THREAD

**Issue by dschnare** [feathersjs/rest-client#35]
Since the code base has interpolated strings throughout, when bundling with Webpack/Nextjs we can't load the client bundle in IE 11 or browsers that do not support interpolated strings. This occurs because Webpack does not compile modules installed using `node_modules` it just bundles them.

Related https://github.com/feathersjs/errors/pull/117

**Comment by daffl** [comment]
How to use Feathers on the client is [documented in the client API chapter](https://docs.feathersjs.com/api/client.html). You have to either

- [Configure your module loader to include modules in the @feathersjs namespace for transpilation](https://docs.feathersjs.com/api/client.html#module-loaders) or
- Use the already pre-transpiled [@feathersjs/client](https://docs.feathersjs.com/api/client.html#feathersjsclient) package which is compatible with IE10+ (as long as ES6 polyfills like core-js are included)
